### ISSUE TITLE
ВАЖЛИВО! ПИТАННЯ ЛОГІНУ ТА РЕЄСТРАЦІЇ!

### ISSUE THREAD

**Issue by Abondarenko29** [sanyaswee/infocygan#3]
Як ми будемо робити робити реєстрацію та логін? Ми будемо використовувати функції django, чи власні функції та шаблони (html файли)? Бо, як я знаю, у django є своя функція для логіну та реєстрації, яка може перевірити електронну пошту. Та, можливо, ще якісь фічі.

**Comment by sanyaswee** [comment]
Ну, наскільки я зрозумів, вже існуючу форму можна підв'язати під якусь модель через POST запит. Думаю ще можливо підключити ці форми до існуючої  моделі django.auth

**Comment by Abondarenko29** [comment]
Треба питати вчителя, просто він радить використовувати застосунок django для логіну та реєстрації.
